# Берем нужный базовый образ
FROM python:3.11-alpine

WORKDIR /app

# Копируем все файлы из текущей директории в /app контейнера
COPY reg_bot/* cfg *.py ./

RUN mkdir temp && \
    mkdir imgs && \
    mkdir db && \
    mkdir /root/.streamlit && \
    echo "[general]" >> /root/.streamlit/credentials.toml && \
    echo "email = \"\"" >>/root/.streamlit/credentials.toml

# Устанавливаем все зависимости
RUN pip install -r requirements.txt --no-cache-dir

VOLUME /app/imgs
VOLUME /app/db

ENTRYPOINT ["python", "bot.py"]