# Берем нужный базовый образ
FROM python:3.11-alpine

WORKDIR /app

# Копируем все файлы из текущей директории в /app контейнера
COPY reg_bot/* cfg *.py ./

# Устанавливаем все зависимости и создаем конфигурационные файлы
RUN mkdir /root/.streamlit && \
    echo "[general]" >> /root/.streamlit/credentials.toml && \
    echo "email = \"\"" >>/root/.streamlit/credentials.toml && \
    pip install -r requirements.txt --no-cache-dir

VOLUME /app/imgs
VOLUME /app/db

ENTRYPOINT ["python", "bot.py"]